### ISSUE TITLE
Relicensing to MIT No Attribution (SPDX: MIT-0)

### ISSUE THREAD

**Issue by hroncok** [hroncok/3dprinter-udev-rules#4]
Considering Fedora is [going to prohibit CC0 for code](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/) at least for new packages, I'd like to relicense this to [MIT No Attribution](https://opensource.org/licenses/MIT-0) (SPDX: *MIT-0*).

@spotrh @yarda Is that OK?

**Comment by yarda** [comment]
For me it's OK.

**Comment by spotrh** [comment]
Fine with me.
